packages/analyzer/src/create.js

Allows plugin authors to use `dev`

feat: pass `dev` to context

---

packages/analyzer/src/features/framework-plugins/lit/static-properties.js

In the issue linked is a case where litelement parser crashes on a default export. There are conditional chaining for [this property in other lit files](https://github.com/open-wc/custom-elements-manifest/blob/15a8c6aafcd4f1675fd5c3eaee1c98f543f5867e/packages/analyzer/src/features/framework-plugins/lit/property-decorator.js#L44), and even in [the initializer of the variable](https://github.com/open-wc/custom-elements-manifest/blob/15a8c6aafcd4f1675fd5c3eaee1c98f543f5867e/packages/analyzer/src/features/framework-plugins/lit/static-properties.js#L17), so there should also be ones in the accessors to prevent undefined access

Fix(analyzer): Fixes #26: CurrClass conditional chaining in litelement parser

---

packages/analyzer/src/utils/cli.js

Stencil components are written in .tsx rather than .ts or .js. The current implementation uses the component's type definitions ('dist/types/components/my-component/my-component.d.ts') instead of the source ('src/components/my-component/my-component.tsx'). While this works, there's a drawback in that prop names won't get properly converted to kebab case if an attribute is not set. Stencil's doc gen does this by default so I suspect a lot of Stencil developers aren't manually defining their prop attributes. 
If I have a prop:
```
@Prop() firstName: string;
```
or even
```
@Prop({attribute: 'first-name') firstName: string;
```
and I run `npx @custom-elements-manifest/analyzer analyze --stencil`, my prop will be output as `firstName` instead of the expected `first-name`. 
To get around this, …

feat: include tsx files in default globs

---

packages/analyzer/src/utils/cli.js

Running the analyser locally on windows with an outdir configured:
`custom-elements-manifest analyze --litelement --globs \"**/*.js\" --outdir \"cem\"`
was replacing the customElements property in package.json with `"customElements": "cem\\custom-elements.json"` instead of `cem/custom-elements.json`.
This adjusts the `addCustomElementsPropertyToPackageJson` function to use `path.posix.join` to ensure it is always written as a posix path.

ensure posix path added to package.json

---

packages/analyzer/src/utils/ast-helpers.js

Some minifiers like to re-assign window functions, and while fiddling with the analyzer on minified files, I noticed that if the window.customElements.define -call gets re-defined, the analyzer breaks.
Playground: https://custom-elements-manifest.netlify.app/?source=dmFyIG49d2luZG93LmN1c3RvbUVsZW1lbnRzLmRlZmluZTsKCmNsYXNzIE15RWxlbWVudCBleHRlbmRzIEhUTUxFbGVtZW50IHsKICBzdGF0aWMgZ2V0IG9ic2VydmVkQXR0cmlidXRlcygpIHsKICAgIHJldHVybiBbJ2Rpc2FibGVkJ107CiAgfQoKICBzZXQgZGlzYWJsZWQodmFsKSB7CiAgICB0aGlzLl9fZGlzYWJsZWQgPSB2YWw7CiAgfQogIGdldCBkaXNhYmxlZCgpIHsKICAgIHJldHVybiB0aGlzLl9fZGlzYWJsZWQ7CiAgfQoKICBmaXJlKCkgewogICAgdGhpcy5kaXNwYXRjaEV2ZW50KG5ldyBFdmVudCgnZGlzYWJsZWQtY2hhbmdlZCcpKTsKICB9Cn0KCm4oJ215LWVsZW1lbnQnLCBNeUVsZW1lbnQpOwo%3D&library=null
---
To make sure it's actually a define CALL and not …

Fix: custom element define re-assign crashes analyzer

---

packages/analyzer/CHANGELOG.md
packages/analyzer/custom-elements.json
packages/analyzer/fixtures/-default/package/bar.js
packages/analyzer/fixtures/class-fields/fixture/custom-elements.json
packages/analyzer/fixtures/class-fields/package/my-element.js
packages/analyzer/src/features/analyse-phase/creators/handlers.js

Bundlers sometimes optimize boolean values to from `true`to `!0` and `false` to `!1`. These are currently recognized as numbers, even though they are boolean values.
A small fix to handle this kind of state correctly.

Fix: PrefixUnaryExpression to check between boolean and number

---

packages/analyzer/index.js
packages/analyzer/src/utils/cli.js
packages/find-dependencies/README.md

It would be nice if the default CLI message would show the installed version of the analyser.
I have added parsing the version from the package's `package.json` file.

Adds version from package.json to the default CLI message

---

docs/analyzer/getting-started.md

I was searching the docs for information on how to ignore certain fields in a custom element when generating the CEM.
I found the answer in a Slack thread, so I thought the docs could use an update on that topic 😜 
Also, the generated `custom-elements.json` example in the `getting-started.md` seemed to be a bit outdated.

chore: documentation on `@internal`/`@ignore`

---

packages/analyzer/cli.js
packages/analyzer/src/utils/cli-helpers.js

`--quiet` prevents the analyzer from outputting: 
```
[2:24:02 PM] @custom-elements-manifest/analyzer: Created new manifest.
```
Help when running `cem analyse` in a chain of other build scripts.
I chose `quiet` because `sass` and `storybook` both use it instead of `silent`.
Fixes #175.

Add `--quiet` cli parameter.

---

packages/analyzer/CHANGELOG.md
packages/analyzer/fixtures/02-inheritance/05-external-in-monorepo/fixture/custom-elements.json
packages/analyzer/fixtures/02-inheritance/05-external-in-monorepo/monorepo/packages/to-be-analyzed-pkg/index.js
packages/analyzer/fixtures/02-inheritance/05-external-in-monorepo/monorepo/packages/to-be-analyzed-pkg/internalFile.js
packages/analyzer/fixtures/02-inheritance/05-external-in-monorepo/output.json
packages/analyzer/package.json
packages/analyzer/src/utils/find-external-manifests.js

When running the latest release in Lion, we found that it breaks for packages that have internal references (it tries to read custom-elements.json that does not exist yet).
These few lines of code in 'find-external-manifests.js' fix this

fix(analyzer): filter out internal manifests

---

packages/analyzer/docs/plugins.md

I just noticed the last phase was named wrong here.

docs: typo fix

---

packages/analyzer/cem.js
packages/analyzer/index.js
packages/analyzer/package.json

This will avoid typescript version mismatch when using the analyzer programatically between the internal version and the user version of typescript.

Expose typescript for programatic use

---

packages/analyzer/fixtures/07-plugin-lit/01-basic/fixture/custom-elements.json
packages/analyzer/fixtures/07-plugin-lit/01-basic/output.json
packages/analyzer/src/features/framework-plugins/lit/static-properties.js
packages/analyzer/src/features/framework-plugins/lit/utils.js

Hi, 
I expected that `npx cem analyze --litelement` would extract types from static properties without any additional `jsdoc` comments.
```js
class MyElement extends LitElement {
static get properties() {
return {
name: { type: String },
active: { type: Boolean },
}
}
```
The benefits are:
- More types in documentation out of the box,
- and if you are using [api-viewer-element](https://github.com/open-wc/api-viewer-element) more knobs works automatically
I have down-cased type to be the same as others and that the knobs are working in `api-viewer-element`.

feat: Lit - extract type from static properties

---

packages/analyzer/src/utils/ast-helpers.js

thanks for a great package!
this adds support for using `globalThis.customElements.define()` which could be more and more used in the future.
we recently changed our library to use `globalThis.customElements.define()` to avoid polluting `window`
https://github.com/muxinc/media-chrome/commit/f620c1ea37c6618d9c621a983baa088e8f9b6f0d
and the `tagName`'s disappeared from the custom elements manifest...

fix: add support for globalThis.customElements

---

docs/analyzer/plugins/intro.md

I added some of the new plugins I had created as well as reformatted this list to a table to make it easier to read

update plugins list

---

docs/analyzer/getting-started.md
packages/analyzer/fixtures/01-class/05-custom-states/fixture/custom-elements.json
packages/analyzer/fixtures/01-class/05-custom-states/output.json
packages/analyzer/fixtures/01-class/05-custom-states/package/my-element.js
packages/analyzer/src/features/analyse-phase/class-jsdoc.js
packages/analyzer/src/features/analyse-phase/creators/createClass.js
packages/analyzer/src/features/link-phase/cleanup-classes.js
packages/analyzer/src/features/post-processing/apply-inheritance.js

Fixes #246 
I went with `@customState` instead of `@state` to disambiguate from `@state()` decorator from Lit.

Add support for custom states

---

packages/analyzer/src/features/analyse-phase/creators/handlers.js

The check here is that `node.name` can be undefined; we then know that the node is private.  But `node.name.text` can be undefined, and that should also not throw an exception at this check. I've added a small check to ensure this won't throw.

web: don't fail when `name.text` is undefined

---

packages/analyzer/src/utils/cli-helpers.js

The documentation [here](https://custom-elements-manifest.open-wc.org/analyzer/config/#cli-options) states that the default configuration for `packagejson` is true but it doesn't seem to come through and has to be added.

fix: add default packagejson config for analyzer

---

packages/find-dependencies/package.json

Adding missing `repo` field to `packages/find-dependencies/package.json` to improve the scans made with SNYK tools of the `@custom-elements-manifest/find-dependencies` package.

chore: added repo field to find-dependencies package.json

---

docs/_assets/theme.css

When hovering over a `<code-tabs>` button while in light mode, the hover state flips from the primary text color, which is nearly black (#2c3e50) on a light gray, to white, which isn't visible on the light background. This is due to the failover which is currently being used since `--code-button-focus-color` is currently undefined. Since there's a light/dark theme here and it seems like the inherited text color is already used, I just set the current color to 75% opacity (which was what was already happening, particularly on the dark theme). So, no visible change for dark, just apply the same change for white.
Note: I'm using `color-mix()` here but support for it is very good and growing (~92% which is pretty decent). See: https://caniuse.com/mdn-css_types_color_color-mix. Not to mention …

fix: code tab hover color in light mode (minor a11y issue)

---

packages/analyzer/fixtures/08-plugin-stencil/01-basic/output.json
packages/analyzer/src/features/framework-plugins/stencil/stencil.js

Fixes #285 
The stencil plugin now correctly populates the artificially created attribute for a field with `default` and `description` from the detected member (if present), where it did not before:
| stencil code | output |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/610ff0f8-bee7-4a0d-a16e-c817af434a58) | ![image](https://github.com/user-attachments/assets/55d848bd-90ca-4b76-8b2f-2c2929790242) | 
I investigated using [handleDefaultValue](https://github.com/open-wc/custom-elements-manifest/blob/master/packages/analyzer/src/features/analyse-phase/creators/handlers.js#L282) per https://github.com/open-wc/custom-elements-manifest/issues/285#issuecomment-2521717424, but I don't think that function applies.
This is an artificially created attribute [being …

feat: `--stencil` now outputs `default` & `description` for attributes

---

packages/analyzer/cli.js

`--watch` mode seems to have 2 issues:
- newly created files are not detected, and the manifest is not re-generated,
- it crashes whenever a watched file is deleted.
This PR aims at fixing both issues.

fix: detect newly added files & fix crash on file deletion

---

packages/analyzer/fixtures/09-plugin-fast/02-test-boolean-attr/fixture/custom-elements.json
packages/analyzer/fixtures/09-plugin-fast/02-test-boolean-attr/package/my-element.js
packages/analyzer/src/features/framework-plugins/decorators/attr.js

When using `@attr({ mode: "boolean" })`, the analyzer was filtering out the "name" field from the attribute manifest output. The attribute would appear without a name field, unlike `@attr` (which uses field name) or `@attr({ attribute: "custom-name" })` (which uses explicit name).
In `attr.js`, when an options object existed but had no `attribute` property, the code was setting `attribute.name = undefined`, overwriting the correctly set field name.
Added a null check to only set `attribute.name` when an explicit name is actually provided:
```javascript
if(name) {
attribute.name = name;
}
```
Closes: #313 
Test Cases
✅ @attr normalAttr → [name: "normalAttr"]
✅ @attr({ attribute: "custom-name" }) → [name: "custom-name"] (explicit name)
✅ @attr({ mode: "boolean" }) booleanAttr → [name: …

Fix: Preserve attribute name when @attr decorator has options without explicit attribute name
